System hostname = kyriakon-restore-template
Password for root account = *************
Public ssh key for root account = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFvWcMN1mB46y9E9diUw+c9S4AP0S7fYCvvwa1NyKzgj oliver@kyriakon.net
What timezone are you in = UTC
Location of sets = http
HTTP Server = cdn.openbsd.org
Encrypt the root disk with a (p)assphrase or (k)eydisk = no
